# Configuration file to run ci tests in docker containers
#
# Defines a database container with MySQL and a container with the environment
# to build libdrizzle-redux. The latter container runs either ubuntu or centos
# depending on the travis build configuration.
#
# See https://docs.docker.com/compose/overview/ for more information about
# the format of the docker compose config file
version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - ./docker/mysql.env
    container_name: mysql-container
    volumes:
      - "mysql_socket:/tmp/"
      - "ssl_certs:/var/lib/mysql"
      - ./docker/mysqld_binlog.cnf:/etc/mysql/mysql.conf.d/mysqld_binlog.cnf
    logging:
      driver: none

  libdrizzle:
    env_file:
      - ./docker/mysql.env
      - ./docker/libdrizzle-redux.env
    environment:
    # environment variables interpolated from travis
      COMPILER_VERSION: $COMPILER_VERSION
      MAKE_TARGET: $MAKE_TARGET
      DIST_NAME: $DIST_NAME
      CXX: $DOCKER_CXX
      CC: $DOCKER_CC
      DRIZZLE_MYSQL_CA_PATH: "/home/ssl-certs"
      CONFIGURE_ARGS: $CONFIGURE_ARGS
    build:
      dockerfile: ./docker/Dockerfile.$DIST_NAME.$DIST_VERSION
      context: ./
    depends_on:
      - db
    container_name: libdrizzle-redux-container
    links:
      - db:database
    volumes:
      - "mysql_socket:/tmp/"
      - "ssl_certs:/home/ssl-certs"
      - ./:/home/libdrizzle-redux/
      - ./docker/entrypoint.$DIST_NAME.sh:/usr/local/bin/entrypoint.$DIST_NAME.sh
      - ./docker/container_entrypoint.sh:/usr/local/bin/container_entrypoint.sh
    working_dir: /home/libdrizzle-redux/
    entrypoint:
      - container_entrypoint.sh

# volume used to share mysql socket between containers
volumes:
  mysql_socket: {}
  ssl_certs: {}
